rg_name: prod-ahubtech
location: eastus

compute:
  vm:
    size: Standard_B1s
    vnet_name: default_vnet
    snet_name: default_snet
    disable_pw_auth: false
    storage_image_reference:
      publisher: "Canonical"
      offer: "0001-com-ubuntu-server-focal"
      sku: "20_04-lts-gen2"
      version: "latest"
    os_disk:
      name: os-disk
      caching: ReadWrite
      create_option:
      managed_disk_type:
      disk_size_gb:
